data("AirPassengers")
print(AirPassengers)
class(AirPassengers)
methods(class="ts")
components <- decompose(AirPassengers)
plot(components)
plot(components$seasonal)

AP.1960 <- window(AirPassengers, start=c(1960,1), end=c(1960,12))
quarterly_means <- colMeans(matrix(AP.1960, nrow=3))
print(quarterly_means)

data.1950 <- window(AirPassengers, start = c(1950,1), freq = TRUE)
data.1954 <- window(AirPassengers, start = c(1954,1), freq = TRUE)
change <- mean(data.1950)/mean(data.1954)
print(change*100)

install.packages('forecast')
library(forecast)
model <- auto.arima(AirPassengers)
summary(model)
forecast_result <- forecast(model, h=24)
print('predicted value in December 1962:')
print(forecast_result$mean[24])

acf(residuals(model), main="ACF of Model Residuals")
test_result <- Box.test(residuals(model), lag=10, type="Ljung-Box")
print(test_result)


data <- read.csv('WK11_data.csv')
data.ts <- ts(data$co2, start = c(1970,1), freq=12)
print(data.ts)
plot(data.ts)
summary(data.ts)
sd(data.ts)
decomp <- decompose(data.ts)
plot(decomp)
plot(data.ts - decomp$seasonal)
sd(data.ts - decomp$seasonal)

annual.data <- aggregate(data.ts)
layout(2:1)
plot(data.ts)
plot(annual.data)
